print_sql: false
host: "0.0.0.0"
port: 80
database_url: "sqlite+aiosqlite:////data/database.db"
run_migration: false

jwt_secret: "{{ UJWT_SECRET }}" # 用于生成 jwt token，需要自行设置
jwt_lifetime_seconds: 86400
cookie_max_age: 86400 # 登录过期时间
user_secret: "{{ UUSER_SECRET }}" # 用于生成用户密码，需要自行设置

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用
create_initial_admin_user: true # 是否创建初始管理员用户
create_initial_user: true # 是否创建初始普通用户
initial_admin_username: "{{ UINITIAL_ADMIN_USERNAME }}" # 初始管理员用户名
initial_admin_password: "{{ UINITIAL_ADMIN_PASSWORD }}" # 初始管理员密码
initial_user_username: "{{ UINITIAL_USER_USERNAME }}" # 初始普通用户名
initial_user_password: "{{ UINITIAL_USER_PASSWORD }}" # 初始普通密码
ask_timeout: 600

chatgpt_access_token: "{{ UCHATGPT_ACCESS_TOKEN }}" # 需要从 ChatGPT 获取
chatgpt_paid: true # 是否为 ChatGPT Plus 用户

log_dir: /app/logs  # 日志存储位置
console_log_level: DEBUG

# chatgpt_base_url: http://127.0.0.1:6062/api/
chatgpt_base_url: https://aabb.co.in/api
run_reverse_proxy: false
reverse_proxy_port: 6062
reverse_proxy_binary_path: /app/backend/ChatGPT-Proxy-V4
reverse_proxy_puid: "{{ UREVERSE_PROXY_PUID }}"
